// <auto-generated />
using System;
using CNPM_LIBRARY_MANAGEMENT.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CNPM_LIBRARY_MANAGEMENT.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CNPM_LIBRARY_MANAGEMENT.Data.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarNguoiDung")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GioiThieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IdnguoiDung")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("IDNguoiDung")
                        .HasComputedColumnSql("('USER'+right('000'+CONVERT([varchar](3),[ID]),(3)))", true);

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("User");

                    b.Property<string>("TenNguoiDung")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Accounts__3214EC2723585D18");

                    b.HasIndex(new[] { "Gmail" }, "IX_Accounts_Gmail");

                    b.HasIndex(new[] { "Gmail" }, "UQ__Accounts__B488B103D1E1DFBE")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("CNPM_LIBRARY_MANAGEMENT.Data.Models.GioHangItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("GioHangItem");
                });

            modelBuilder.Entity("CNPM_LIBRARY_MANAGEMENT.Data.Models.ChatLieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaChatLieu")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)")
                        .HasComputedColumnSql("('CL'+right('00'+CONVERT([varchar](2),[ID]),(2)))", true);

                    b.Property<string>("TenChatLieu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__ChatLieu__3214EC27F776C123");

                    b.HasIndex(new[] { "TenChatLieu" }, "UQ__ChatLieu__7FE6CCCAB2BD0100")
                        .IsUnique();

                    b.ToTable("ChatLieu", (string)null);
                });

            modelBuilder.Entity("CNPM_LIBRARY_MANAGEMENT.Data.Models.ChiTietHoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int>("HoaDonId")
                        .HasColumnType("int")
                        .HasColumnName("HoaDonID");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int")
                        .HasColumnName("SanPhamID");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__ChiTietH__3214EC27DB44F1B5");

                    b.HasIndex("HoaDonId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("ChiTietHoaDon", (string)null);
                });

            modelBuilder.Entity("CNPM_LIBRARY_MANAGEMENT.Data.Models.ChiTietSach", b =>
                {
                    b.Property<int>("SanPhamId")
                        .HasColumnType("int")
                        .HasColumnName("SanPhamID");

                    b.Property<string>("KichThuoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LoaiBia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("NgayPhatHanh")
                        .HasColumnType("date");

                    b.Property<int?>("NhaXuatBanId")
                        .HasColumnType("int")
                        .HasColumnName("NhaXuatBanID");

                    b.Property<int?>("SoTrang")
                        .HasColumnType("int");

                    b.Property<int?>("TacGiaId")
                        .HasColumnType("int")
                        .HasColumnName("TacGiaID");

                    b.Property<int>("TheLoaiId")
                        .HasColumnType("int")
                        .HasColumnName("TheLoaiID");

                    b.HasKey("SanPhamId")
                        .HasName("PK__ChiTietS__05180FF432D4D6A7");

                    b.HasIndex("NhaXuatBanId");

                    b.HasIndex("TacGiaId");

                    b.HasIndex("TheLoaiId");

                    b.ToTable("ChiTietSach", (string)null);
                });

            modelBuilder.Entity("CNPM_LIBRARY_MANAGEMENT.Data.Models.ChiTietVpp", b =>
                {
                    b.Property<int>("SanPhamId")
                        .HasColumnType("int")
                        .HasColumnName("SanPhamID");

                    b.Property<int>("IdloaiVpp")
                        .HasColumnType("int")
                        .HasColumnName("IDLoaiVPP");

                    b.Property<int?>("NhaSanXuatId")
                        .HasColumnType("int")
                        .HasColumnName("NhaSanXuatID");

                    b.Property<int?>("ThuongHieuId")
                        .HasColumnType("int")
                        .HasColumnName("ThuongHieuID");

                    b.HasKey("SanPhamId")
                        .HasName("PK__ChiTietV__05180FF4D6B8F4E4");

                    b.HasIndex("IdloaiVpp");

                    b.HasIndex("NhaSanXuatId");

                    b.HasIndex("ThuongHieuId");

                    b.ToTable("ChiTietVPP", (string)null);
                });

            modelBuilder.Entity("CNPM_LIBRARY_MANAGEMENT.Data.Models.DanhGia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<byte>("Sao")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("DanhGias");
                });

            modelBuilder.Entity("CNPM_LIBRARY_MANAGEMENT.Data.Models.HoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    b.Property<string>("DiaChiGiaoHang")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("GiamGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 0)")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("HoTenNguoiNhan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayDatHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Chờ xử lý");

                    b.HasKey("Id")
                        .HasName("PK__HoaDon__3214EC27C5AB1E57");

                    b.HasIndex("AccountId");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("CNPM_LIBRARY_MANAGEMENT.Data.Models.LoaiSanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IdloaiSp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("IDLoaiSP")
                        .HasComputedColumnSql("('L'+right('00'+CONVERT([varchar](2),[ID]),(2)))", true);

                    b.Property<string>("TenLoaiSp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenLoaiSP");

                    b.HasKey("Id")
                        .HasName("PK__LoaiSanP__3214EC27454A2435");

                    b.HasIndex(new[] { "TenLoaiSp" }, "UQ__LoaiSanP__F434DB49100F9A7C")
                        .IsUnique();

                    b.ToTable("LoaiSanPham", (string)null);
                });

            modelBuilder.Entity("CNPM_LIBRARY_MANAGEMENT.Data.Models.LoaiVppham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IdloaiVpp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("IDLoaiVPP")
                        .HasComputedColumnSql("('LVP'+right('00'+CONVERT([varchar](2),[ID]),(2)))", true);

                    b.Property<string>("TenLoaiVpp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenLoaiVPP");

                    b.HasKey("Id")
                        .HasName("PK__LoaiVPPh__3214EC27CC22E15A");

                    b.ToTable("LoaiVPPham", (string)null);
                });

            modelBuilder.Entity("CNPM_LIBRARY_MANAGEMENT.Data.Models.MauSac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaMauSac")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasComputedColumnSql("('MS'+right('00'+CONVERT([nvarchar](2),[ID]),(2)))", true);

                    b.Property<string>("TenMauSac")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__MauSac__3214EC273199FA6A");

                    b.HasIndex(new[] { "TenMauSac" }, "UQ__MauSac__23D77400EA5ED49F")
                        .IsUnique();

                    b.ToTable("MauSac", (string)null);
                });

            modelBuilder.Entity("CNPM_LIBRARY_MANAGEMENT.Data.Models.NhaSanXuat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaNsx")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("MaNSX")
                        .HasComputedColumnSql("('NSX'+right('000'+CONVERT([nvarchar](3),[ID]),(3)))", true);

                    b.Property<string>("TenNsx")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenNSX");

                    b.HasKey("Id")
                        .HasName("PK__NhaSanXu__3214EC2786F08741");

                    b.ToTable("NhaSanXuat", (string)null);
                });

            modelBuilder.Entity("CNPM_LIBRARY_MANAGEMENT.Data.Models.NhaXuatBan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaNxb")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("MaNXB")
                        .HasComputedColumnSql("('NXB'+right('000'+CONVERT([varchar](3),[ID]),(3)))", true);

                    b.Property<string>("TenNxb")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenNXB");

                    b.HasKey("Id")
                        .HasName("PK__NhaXuatB__3214EC2791B538D0");

                    b.HasIndex(new[] { "TenNxb" }, "UQ__NhaXuatB__CCE3868DF879A71E")
                        .IsUnique();

                    b.ToTable("NhaXuatBan", (string)null);
                });

            modelBuilder.Entity("CNPM_LIBRARY_MANAGEMENT.Data.Models.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte?>("DanhGia")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("LoaiSanPhamId")
                        .HasColumnType("int")
                        .HasColumnName("LoaiSanPhamID");

                    b.Property<string>("MaSp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("MaSP")
                        .HasComputedColumnSql("('SP'+right('00000'+CONVERT([varchar](5),[ID]),(5)))", true);

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("NgayDang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("SoLuongDaBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("TrongLuong")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__SanPham__3214EC274653BBA8");

                    b.HasIndex("LoaiSanPhamId");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("CNPM_LIBRARY_MANAGEMENT.Data.Models.TacGium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaTacGia")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasComputedColumnSql("('TG'+right('000'+CONVERT([varchar](3),[ID]),(3)))", true);

                    b.Property<string>("TenTacGia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__TacGia__3214EC27579F2477");

                    b.ToTable("TacGia");
                });

            modelBuilder.Entity("CNPM_LIBRARY_MANAGEMENT.Data.Models.TheLoaiSach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaTheLoai")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasComputedColumnSql("('TLS'+right('00'+CONVERT([varchar](2),[ID]),(2)))", true);

                    b.Property<string>("TenTheLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__TheLoaiS__3214EC273E2B81FF");

                    b.HasIndex(new[] { "TenTheLoai" }, "UQ__TheLoaiS__327F958F9319C08A")
                        .IsUnique();

                    b.ToTable("TheLoaiSach", (string)null);
                });

            modelBuilder.Entity("CNPM_LIBRARY_MANAGEMENT.Data.Models.ThuongHieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaThuongHieu")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasComputedColumnSql("('TT'+right('000'+CONVERT([varchar](3),[ID]),(3)))", true);

                    b.Property<string>("TenThuongHieu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__ThuongHi__3214EC27D19FB015");

                    b.HasIndex(new[] { "TenThuongHieu" }, "UQ__ThuongHi__98D6A8341293E8CF")
                        .IsUnique();

                    b.ToTable("ThuongHieu", (string)null);
                });

            modelBuilder.Entity("CNPM_LIBRARY_MANAGEMENT.Data.Models.YeuThich", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThem")
                        .HasColumnType("datetime2");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("YeuThich");
                });

            modelBuilder.Entity("SanPhamVppChatLieu", b =>
                {
                    b.Property<int>("SanPhamVppId")
                        .HasColumnType("int")
                        .HasColumnName("SanPhamVPP_ID");

                    b.Property<int>("ChatLieuId")
                        .HasColumnType("int")
                        .HasColumnName("ChatLieuID");

                    b.HasKey("SanPhamVppId", "ChatLieuId")
                        .HasName("PK__SanPhamV__C2BDD873D903A74D");

                    b.HasIndex("ChatLieuId");

                    b.ToTable("SanPhamVPP_ChatLieu", (string)null);
                });

            modelBuilder.Entity("SanPhamVppMauSac", b =>
                {
                    b.Property<int>("SanPhamVppId")
                        .HasColumnType("int")
                        .HasColumnName("SanPhamVPP_ID");

                    b.Property<int>("MauSacId")
                        .HasColumnType("int")
                        .HasColumnName("MauSacID");

                    b.HasKey("SanPhamVppId", "MauSacId")
                        .HasName("PK__SanPhamV__CFC60C5D9F1A39B5");

                    b.HasIndex("MauSacId");

                    b.ToTable("SanPhamVPP_MauSac", (string)null);
                });

            modelBuilder.Entity("CNPM_LIBRARY_MANAGEMENT.Data.Models.GioHangItem", b =>
                {
                    b.HasOne("CNPM_LIBRARY_MANAGEMENT.Data.Models.Account", "Account")
                        .WithMany("GioHangItems")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GioHangItem_Accounts_AccountId");

                    b.HasOne("CNPM_LIBRARY_MANAGEMENT.Data.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GioHangItem_SanPham_SanPhamId");

                    b.Navigation("Account");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("CNPM_LIBRARY_MANAGEMENT.Data.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("CNPM_LIBRARY_MANAGEMENT.Data.Models.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietHo__HoaDo__4D94879B");

                    b.HasOne("CNPM_LIBRARY_MANAGEMENT.Data.Models.SanPham", "SanPham")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("SanPhamId")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietHo__SanPh__4E88ABD4");

                    b.Navigation("HoaDon");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("CNPM_LIBRARY_MANAGEMENT.Data.Models.ChiTietSach", b =>
                {
                    b.HasOne("CNPM_LIBRARY_MANAGEMENT.Data.Models.NhaXuatBan", "NhaXuatBan")
                        .WithMany("ChiTietSaches")
                        .HasForeignKey("NhaXuatBanId")
                        .HasConstraintName("FK__ChiTietSa__NhaXu__3C69FB99");

                    b.HasOne("CNPM_LIBRARY_MANAGEMENT.Data.Models.SanPham", "SanPham")
                        .WithOne("ChiTietSach")
                        .HasForeignKey("CNPM_LIBRARY_MANAGEMENT.Data.Models.ChiTietSach", "SanPhamId")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietSa__SanPh__398D8EEE");

                    b.HasOne("CNPM_LIBRARY_MANAGEMENT.Data.Models.TacGium", "TacGia")
                        .WithMany("ChiTietSaches")
                        .HasForeignKey("TacGiaId")
                        .HasConstraintName("FK__ChiTietSa__TacGi__3B75D760");

                    b.HasOne("CNPM_LIBRARY_MANAGEMENT.Data.Models.TheLoaiSach", "TheLoai")
                        .WithMany("ChiTietSaches")
                        .HasForeignKey("TheLoaiId")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietSa__TheLo__3A81B327");

                    b.Navigation("NhaXuatBan");

                    b.Navigation("SanPham");

                    b.Navigation("TacGia");

                    b.Navigation("TheLoai");
                });

            modelBuilder.Entity("CNPM_LIBRARY_MANAGEMENT.Data.Models.ChiTietVpp", b =>
                {
                    b.HasOne("CNPM_LIBRARY_MANAGEMENT.Data.Models.LoaiVppham", "IdloaiVppNavigation")
                        .WithMany("ChiTietVpps")
                        .HasForeignKey("IdloaiVpp")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietVP__IDLoa__403A8C7D");

                    b.HasOne("CNPM_LIBRARY_MANAGEMENT.Data.Models.NhaSanXuat", "NhaSanXuat")
                        .WithMany("ChiTietVpps")
                        .HasForeignKey("NhaSanXuatId")
                        .HasConstraintName("FK__ChiTietVP__NhaSa__4222D4EF");

                    b.HasOne("CNPM_LIBRARY_MANAGEMENT.Data.Models.SanPham", "SanPham")
                        .WithOne("ChiTietVpp")
                        .HasForeignKey("CNPM_LIBRARY_MANAGEMENT.Data.Models.ChiTietVpp", "SanPhamId")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietVP__SanPh__3F466844");

                    b.HasOne("CNPM_LIBRARY_MANAGEMENT.Data.Models.ThuongHieu", "ThuongHieu")
                        .WithMany("ChiTietVpps")
                        .HasForeignKey("ThuongHieuId")
                        .HasConstraintName("FK__ChiTietVP__Thuon__412EB0B6");

                    b.Navigation("IdloaiVppNavigation");

                    b.Navigation("NhaSanXuat");

                    b.Navigation("SanPham");

                    b.Navigation("ThuongHieu");
                });

            modelBuilder.Entity("CNPM_LIBRARY_MANAGEMENT.Data.Models.DanhGia", b =>
                {
                    b.HasOne("CNPM_LIBRARY_MANAGEMENT.Data.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CNPM_LIBRARY_MANAGEMENT.Data.Models.SanPham", "SanPham")
                        .WithMany("DanhGias")
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("CNPM_LIBRARY_MANAGEMENT.Data.Models.HoaDon", b =>
                {
                    b.HasOne("CNPM_LIBRARY_MANAGEMENT.Data.Models.Account", "Account")
                        .WithMany("HoaDons")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__HoaDon__AccountI__173876EA");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CNPM_LIBRARY_MANAGEMENT.Data.Models.SanPham", b =>
                {
                    b.HasOne("CNPM_LIBRARY_MANAGEMENT.Data.Models.LoaiSanPham", "LoaiSanPham")
                        .WithMany("SanPhams")
                        .HasForeignKey("LoaiSanPhamId")
                        .IsRequired()
                        .HasConstraintName("FK__SanPham__LoaiSan__35BCFE0A");

                    b.Navigation("LoaiSanPham");
                });

            modelBuilder.Entity("CNPM_LIBRARY_MANAGEMENT.Data.Models.YeuThich", b =>
                {
                    b.HasOne("CNPM_LIBRARY_MANAGEMENT.Data.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CNPM_LIBRARY_MANAGEMENT.Data.Models.SanPham", "SanPham")
                        .WithMany("YeuThichs")
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("SanPhamVppChatLieu", b =>
                {
                    b.HasOne("CNPM_LIBRARY_MANAGEMENT.Data.Models.ChatLieu", null)
                        .WithMany()
                        .HasForeignKey("ChatLieuId")
                        .IsRequired()
                        .HasConstraintName("FK__SanPhamVP__ChatL__49C3F6B7");

                    b.HasOne("CNPM_LIBRARY_MANAGEMENT.Data.Models.ChiTietVpp", null)
                        .WithMany()
                        .HasForeignKey("SanPhamVppId")
                        .IsRequired()
                        .HasConstraintName("FK__SanPhamVP__SanPh__48CFD27E");
                });

            modelBuilder.Entity("SanPhamVppMauSac", b =>
                {
                    b.HasOne("CNPM_LIBRARY_MANAGEMENT.Data.Models.MauSac", null)
                        .WithMany()
                        .HasForeignKey("MauSacId")
                        .IsRequired()
                        .HasConstraintName("FK__SanPhamVP__MauSa__45F365D3");

                    b.HasOne("CNPM_LIBRARY_MANAGEMENT.Data.Models.ChiTietVpp", null)
                        .WithMany()
                        .HasForeignKey("SanPhamVppId")
                        .IsRequired()
                        .HasConstraintName("FK__SanPhamVP__SanPh__44FF419A");
                });

            modelBuilder.Entity("CNPM_LIBRARY_MANAGEMENT.Data.Models.Account", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("GioHangItems");
                });

            modelBuilder.Entity("CNPM_LIBRARY_MANAGEMENT.Data.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("CNPM_LIBRARY_MANAGEMENT.Data.Models.LoaiSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("CNPM_LIBRARY_MANAGEMENT.Data.Models.LoaiVppham", b =>
                {
                    b.Navigation("ChiTietVpps");
                });

            modelBuilder.Entity("CNPM_LIBRARY_MANAGEMENT.Data.Models.NhaSanXuat", b =>
                {
                    b.Navigation("ChiTietVpps");
                });

            modelBuilder.Entity("CNPM_LIBRARY_MANAGEMENT.Data.Models.NhaXuatBan", b =>
                {
                    b.Navigation("ChiTietSaches");
                });

            modelBuilder.Entity("CNPM_LIBRARY_MANAGEMENT.Data.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietHoaDons");

                    b.Navigation("ChiTietSach");

                    b.Navigation("ChiTietVpp");

                    b.Navigation("DanhGias");

                    b.Navigation("YeuThichs");
                });

            modelBuilder.Entity("CNPM_LIBRARY_MANAGEMENT.Data.Models.TacGium", b =>
                {
                    b.Navigation("ChiTietSaches");
                });

            modelBuilder.Entity("CNPM_LIBRARY_MANAGEMENT.Data.Models.TheLoaiSach", b =>
                {
                    b.Navigation("ChiTietSaches");
                });

            modelBuilder.Entity("CNPM_LIBRARY_MANAGEMENT.Data.Models.ThuongHieu", b =>
                {
                    b.Navigation("ChiTietVpps");
                });
#pragma warning restore 612, 618
        }
    }
}
